# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.provision "puppet"

    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.customize ["modifyvm", :id, "--memory", '1024']
      vb.customize ["modifyvm", :id, "--name", 'xl-helper-demobox']
    end

    config.vm.synced_folder "..", "/world"
end
